---
title: "Data"
---

### Minnesota Lake Ice

<font size="4"> 
All of our Minnesota Ice data came from the [Minnesota DNR](https://www.dnr.state.mn.us/ice_out/index.html). All of the physical lake characteristics such as depth, came from the Minnesota [Geospatial Commons](https://gisdata.mn.gov/dataset/water-lake-bathymetry). In some instances we had to manually enter depth (or other lake characteristics) because it was not available through the Geospatial Commons. In these instances, we used the mnsentinellakes package through R to access DNR surveys. These surveys can also be found by using MN DNR's [Lake Finder Website](https://www.dnr.state.mn.us/lakefind/index.html). Thank you to the DNR for creating these amazing resources and make sure to check them out! They also have cool ice and lake stuff. Finally, all the climatic variables used in the lake ice analysis were downloaded through NOAA's [Physical Sciences Laboratory Website](https://psl.noaa.gov/data/climateindices/). 

### Global Sea Ice

Global Sea Ice Data was gathered from the [National Snow and Ice Data Center (NSIDC)](https://nsidc.org/), a collaborative project between the University of Colorado-Boulder and multiple federal agencies, including NASA and NOAA. Global temperature and sea level data were gathered from the climate change collection on [Data Hub](https://datahub.io/collections/climate-change). For sea level, data was based on global measurements gathered by [CSIRO](https://www.cmar.csiro.au/sealevel/sl_hist_last_decades.html), while global temperatures were measured by [NASA's GISTEMP analysis](https://data.giss.nasa.gov/gistemp/). Without such collaborative efforts and remarkable data sharing, none of our global analyses would've been possible.
</font>
